In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("/content/Sample data.xlsx")

In [3]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [4]:
df.shape()

TypeError: 'tuple' object is not callable

In [5]:
df.shape

(700, 16)

In [6]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [7]:
df.columns = df.columns.str.strip()

In [8]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [10]:
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
Sales                   0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [11]:
df["Discount Band"] = df['Discount Band'].fillna('None')

In [12]:
df["Discount Band"].isnull().sum()

np.int64(0)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        700 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9   Sales                700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [18]:
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

In [19]:
df.columns = (df.columns.str.strip().str.lower().str.replace(" ","_"))

In [20]:
df.columns

Index(['segment', 'country', 'product', 'discount_band', 'units_sold',
       'manufacturing_price', 'sale_price', 'gross_sales', 'discounts',
       'sales', 'cogs', 'profit', 'date', 'month_number', 'month_name',
       'year'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   segment              700 non-null    object
 1   country              700 non-null    object
 2   product              700 non-null    object
 3   discount_band        700 non-null    object
 4   units_sold           700 non-null    float64
 5   manufacturing_price  700 non-null    int64
 6   sale_price           700 non-null    int64
 7   gross_sales          700 non-null    float64
 8   discounts            700 non-null    float64
 9   sales                700 non-null    float64
 10  cogs                 700 non-null    float64
 11  profit               700 non-null    float64
 12  date                 700 non-null    datetime64[ns]
 13  month_number         700 non-null    int64
 14  month_name           700 non-null    object
 15  year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [22]:
df.describe()

,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

In [23]:
kpis = {
    "Total Units Sold": df["units_sold"].sum(),
    "Total Gross Sales": df["gross_sales"].sum(),
    "Total Discounts": df["discounts"].sum(),
    "Total Sales": df["sales"].sum(),
    "Total COGS": df["cogs"].sum(),
    "Total Profit": df["profit"].sum()
}

kpis

{'Total Units Sold': np.float64(1125806.0),
 'Total Gross Sales': np.float64(127931598.5),
 'Total Discounts': np.float64(9205248.239999998),
 'Total Sales': np.float64(118726350.25999999),
 'Total COGS': np.float64(101832648.0),
 'Total Profit': np.float64(16893702.26)}

In [24]:
profit_margin = (df["profit"].sum() / df["sales"].sum()) * 100

profit_margin

np.float64(14.229109395685388)

In [25]:
loss_making = df[df["profit"] < 0]

loss_making.shape

(58, 16)

In [26]:
loss_making[["segment", "country", "product", "discount_band", "sales", "cogs", "profit"]]

,segment,country,product,discount_band,sales,cogs,profit
392,Enterprise,United States of America,Montana,Medium,430706.25,435240.0,-4533.75
397,Enterprise,Germany,Velo,Medium,95831.25,96840.0,-1008.75
398,Enterprise,United States of America,Velo,Medium,102243.75,103320.0,-1076.25
399,Enterprise,France,Velo,Medium,83600.00,84480.0,-880.00
406,Enterprise,Germany,Carretera,Medium,104222.50,106440.0,-2217.50
408,Enterprise,Canada,Velo,Medium,111860.00,114240.0,-2380.00
409,Enterprise,United States of America,Velo,Medium,323712.50,330600.0,-6887.50
415,Enterprise,France,Amarilla,Medium,233531.25,238500.0,-4968.75
427,Enterprise,Germany,Montana,Medium,290625.00,300000.0,-9375.00
429,Enterprise,Germany,Velo,Medium,242613.75,250440.0,-7826.25
434,Enterprise,Canada,Amarilla,Medium,191231.25,197400.0,-6168.75
435,Enterprise,Germany,Amarilla,Medium,115552.50,119280.0,-3727.50
437,Enterprise,Mexico,Carretera,Medium,177100.00,184800.0,-7700.00
457,Enterprise,France,Montana,Medium,211233.75,222840.0,-11606.25
458,Enterprise,United States of America,Montana,Medium,318158.75,335640.0,-17481.25
462,Enterprise,Canada,Velo,Medium,64496.25,68040.0,-3543.75
463,Enterprise,Mexico,Velo,Medium,240012.50,253200.0,-13187.50
470,Enterprise,Mexico,VTT,Medium,99758.75,105240.0,-5481.25
478,Enterprise,United States of America,Carretera,High,387618.75,413460.0,-25841.25
479,Enterprise,France,Carretera,High,166725.00,177840.0,-11115.00
480,Enterprise,United States of America,Montana,High,202950.00,216480.0,-13530.00
485,Enterprise,United States of America,Velo,High,179550.00,191520.0,-11970.00
487,Enterprise,Canada,Velo,High,215550.00,229920.0,-14370.00
489,Enterprise,Mexico,VTT,High,38362.50,40920.0,-2557.50
494,Enterprise,Canada,VTT,High,284512.50,303480.0,-18967.50
495,Enterprise,United States of America,Amarilla,High,65137.50,69480.0,-4342.50
509,Enterprise,France,Carretera,High,271561.25,292920.0,-21358.75
514,Enterprise,Mexico,VTT,High,61632.50,66480.0,-4847.50
515,Enterprise,Germany,Amarilla,High,352106.25,379800.0,-27693.75
516,Enterprise,France,Amarilla,High,159421.25,171960.0,-12538.75
517,Enterprise,Mexico,Amarilla,High,105353.75,113640.0,-8286.25
519,Enterprise,Canada,Carretera,High,265760.00,289920.0,-24160.00
520,Enterprise,Mexico,Carretera,High,237160.00,258720.0,-21560.00
527,Enterprise,United States of America,VTT,High,262570.00,286440.0,-23870.00
540,Enterprise,Canada,VTT,High,172151.25,189960.0,-17808.75
542,Enterprise,Canada,Amarilla,High,180416.25,199080.0,-18663.75
548,Enterprise,France,Carretera,High,109972.50,122760.0,-12787.50
553,Enterprise,Mexico,Carretera,High,303257.50,338520.0,-35262.50
555,Enterprise,Mexico,Velo,High,169312.50,189000.0,-19687.50
564,Enterprise,United States of America,Amarilla,High,305730.00,341280.0,-35550.00
569,Enterprise,France,Carretera,High,124737.50,140880.0,-16142.50
570,Enterprise,Germany,Carretera,High,293993.75,332040.0,-38046.25
571,Enterprise,Germany,Carretera,High,115281.25,130200.0,-14918.75
575,Enterprise,France,Velo,High,70443.75,79560.0,-9116.25
577,Enterprise,United States of America,Velo,High,259037.50,292560.0,-33522.50
581,Enterprise,Canada,VTT,High,313862.50,354480.0,-40617.50
582,Enterprise,Germany,VTT,High,58650.00,66240.0,-7590.00
637,Enterprise,United States of America,Paseo,Medium,355300.00,359040.0,-3740.00
638,Enterprise,France,Paseo,Medium,283218.75,286200.0,-2981.25
642,Enterprise,United States of America,Paseo,Medium,102243.75,103320.0,-1076.25
643,Enterprise,France,Paseo,Medium,83600.00,84480.0,-880.00
652,Enterprise,Germany,Paseo,Medium,408386.25,421560.0,-13173.75
658,Enterprise,Mexico,Paseo,Medium,128110.00,133680.0,-5570.00
667,Enterprise,United States of America,Paseo,Medium,318158.75,335640.0,-17481.25
676,Enterprise,France,Paseo,High,271561.25,292920.0,-21358.75
679,Enterprise,Mexico,Paseo,High,237160.00,258720.0,-21560.00
684,Enterprise,Canada,Paseo,High,172151.25,189960.0,-17808.75
697,Enterprise,Germany,Paseo,High,115281.25,130200.0,-14918.75

In [27]:
df.to_excel("cleaned_data.xlsx", index=False)